title: Allison Carr
logo: "/images/allison_logo?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master of City Planning
  <br><br>
  Text
  <br><br>
  <a href="https://www.linkedin.com/in/allisonccarr/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
